### ISSUE TITLE
question

### ISSUE THREAD

**Issue by xiaoheiccc** [WithSecureLabs/C3#70]
Will the C3 project be updated? I need some channel configuration documents very much

**Comment by felixm-pw** [comment]
Hi xiaoheiccc,

I have just updated the Resources folder to contain a collection of guides for setting up Relays (and Channels). Hopefully this has enough information to get you up and running. Please see the following:
[Link to Res/ResourceGuides](https://github.com/WithSecureLabs/C3/tree/master/Res/RelayGuides)

Let me know if this answers your question.

Thanks

**Comment by felixm-pw** [comment]
Hi xiaoheiccc,

If you're looking to create custom channels I would point you towards[ CONTRIBUTING.md](https://github.com/WithSecureLabs/C3/blob/master/CONTRIBUTING.md). In terms of examples for custom channels I think reading the source code for the currently supported ones.

Hope this helps!
