### ISSUE TITLE
Network Error

### ISSUE THREAD

**Issue by xiaoheiccc** [WithSecureLabs/C3#80]
I started Startwebcontroller.cmd and then I visited my localhost: 52935, but he kept prompting Network error, and I couldn't create a new GATEWAY button. It doesn't seem to work

**Comment by felixm-pw** [comment]
Hi xiaoheiccc,
I can confirm the current release version is functional. Please ensure you have [Dotnet 3.1 SDK](https://dotnet.microsoft.com/en-us/download/dotnet/3.1) and all other dependencies installed. 

Thanks,
Felix
