### ISSUE TITLE
Throwing exception: unable to create channel

### ISSUE THREAD

**Issue by k-fire** [WithSecureLabs/C3#82]
Select (double-click) the gateway or relay on which to create the channel.
Open the command centre screen by selecting the “Command Centre” button.
In the “Select Command” dropdown, select a command such as “AddNegotiationChannelSlack”.
Fill out the required information, such as any credentials and application specifics.
Click the “Send Command” button.

![image](https://user-images.githubusercontent.com/40354487/224261038-16ffb783-5a48-43c9-a470-8d27bdb00f19.png)

**Comment by felixm-pw** [comment]
Hi k-fire,
This is a generic error that is usually thrown when the required information for the Channel/Relay is not correct. I can see from this screenshot that you are attempting to set up a Slack based Channel/Relay. Please try following the [Slack Relay Guide](https://github.com/WithSecureLabs/C3/blob/master/Res/RelayGuides/SlackRelayGuide.md) as I can confirm that this is a working feature. Let me know if this works for you!

Thanks,
Felix

**Comment by k-fire** [comment]
> 嗨 k-fire，这是一个通用错误，通常在通道/继电器所需的信息不正确时抛出。我可以从此屏幕截图中看到您正在尝试设置基于 Slack 的频道/中继。请尝试遵循 [松弛中继指南](https://github.com/WithSecureLabs/C3/blob/master/Res/RelayGuides/SlackRelayGuide.md)，因为我可以确认这是一个有效的功能。让我知道这是否适合您！
> 
> 谢谢，菲利克斯

thanks for your reply
